//! Build script for par-term-emu-core-rust
//!
//! Protocol Buffer code is pre-generated in src/streaming/terminal.pb.rs
//! to avoid requiring protoc at build time.
//!
//! To regenerate protobuf code after modifying proto/terminal.proto, run
//! `make proto-rust` (requires protoc). The Makefile also stamps the
//! generated file with a checksum of the proto, which this build script
//! verifies — see `check_proto_staleness`.

fn main() {
    // Regenerate protobuf code only when explicitly requested
    #[cfg(feature = "regenerate-proto")]
    {
        println!("cargo:rerun-if-changed=proto/terminal.proto");

        prost_build::Config::new()
            .compile_protos(&["proto/terminal.proto"], &["proto/"])
            .expect("Failed to compile Protocol Buffer schema. Make sure protoc is installed.");
    }

    // Catch wire-format drift (ARC-020): the checked-in
    // src/streaming/terminal.pb.rs is the build-time source of truth (no protoc
    // dependency), so an edited proto/terminal.proto that wasn't regenerated
    // would silently desync the Rust from the schema. `make proto-rust` stamps
    // the generated file with an FNV-1a checksum of the proto; a mismatch
    // means the proto changed without a regeneration. Content, not mtimes —
    // checkout and clone do not preserve mtime ordering, which made the
    // original mtime comparison fire on every build of an unmodified tree.
    check_proto_staleness();
}

/// FNV-1a 64-bit checksum, matching the stamp written by `make proto-rust`.
///
/// Every `\r` is dropped first: git can check the proto out with CRLF on
/// Windows, and the checksum must not depend on checkout settings. The proto
/// contains no bare `\r`, so this is exactly line-ending normalization.
fn fnv1a_normalized(bytes: &[u8]) -> u64 {
    let mut hash: u64 = 0xcbf29ce484222325;
    for &byte in bytes {
        if byte == b'\r' {
            continue;
        }
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

/// The `// proto-fnv1a:<16 hex>` stamp on the generated file's first line.
fn embedded_checksum(bytes: &[u8]) -> Option<u64> {
    let first_line_end = bytes.iter().position(|&b| b == b'\n')?;
    let line = std::str::from_utf8(&bytes[..first_line_end]).ok()?;
    let hex = line.strip_prefix("// proto-fnv1a:")?;
    u64::from_str_radix(hex.trim(), 16).ok()
}

fn check_proto_staleness() {
    let proto = std::path::Path::new("proto/terminal.proto");
    let checked_in = std::path::Path::new("src/streaming/terminal.pb.rs");

    let (Ok(proto_bytes), Ok(pb_bytes)) = (std::fs::read(proto), std::fs::read(checked_in)) else {
        return;
    };

    println!("cargo:rerun-if-changed=proto/terminal.proto");
    println!("cargo:rerun-if-changed=src/streaming/terminal.pb.rs");

    // No stamp: the file predates checksum stamping (or was regenerated by
    // raw cargo rather than make proto-rust). Nothing to compare against.
    let Some(embedded) = embedded_checksum(&pb_bytes) else {
        return;
    };

    if fnv1a_normalized(&proto_bytes) != embedded {
        println!(
            "cargo:warning=ARC-020: proto/terminal.proto changed without regenerating \
             src/streaming/terminal.pb.rs (checksum mismatch). Run `make proto-rust` \
             and commit the result."
        );
    }
}
