#!/usr/bin/env python3
"""Generate ``python/par_term_emu_core_rust/_native.pyi`` from the built native module.

ARC-002: runtime-introspection stub generation. The PyO3 ``_native`` module is
introspected at runtime (classes, methods, properties, module functions and
constants) and emitted as a parseable ``.pyi`` stub so the
``Typing :: Typed`` classifier is honest.

Usage (requires a built module; ``make dev-streaming`` captures the widest
method surface, ``make dev`` covers the same class/function names):

    uv run python scripts/generate_stubs.py

Known limitations (deliberate, see AUDIT.md ARC-002):
- PyO3 does not expose ``__text_signature__`` for ``#[new]`` constructors, so
  every class gets ``def __init__(self, *args: Any, **kwargs: Any)``.
- All value types are ``Any``: signatures carry parameter names, kinds and
  defaults (the parts PyO3 exposes) but not types.
- Properties are emitted with both a getter and a setter; read-only
  properties are over-promised in the stub (harmless for type checking).

The script self-checks its output with :mod:`ast` and verifies that every
public ``dir()`` member of the module appears in the stub.
"""

from __future__ import annotations

import ast
import keyword
from pathlib import Path

import par_term_emu_core_rust._native as native

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "python" / "par_term_emu_core_rust" / "_native.pyi"

# Members that exist at runtime but cannot be spelled in a stub (Python
# keywords used as attribute names, e.g. UnderlineStyle.None).
SKIPPED_MEMBERS: list[str] = []

# Dunders worth emitting when the class defines them (protocol methods pyright
# checks, e.g. context-manager and conversion protocols).
DUNDER_METHODS = {
    "__init__",
    "__new__",
    "__enter__",
    "__exit__",
    "__aenter__",
    "__aexit__",
    "__iter__",
    "__next__",
    "__len__",
    "__getitem__",
    "__setitem__",
    "__contains__",
    "__call__",
    "__int__",
    "__float__",
    "__str__",
    "__index__",
    "__copy__",
    "__deepcopy__",
    "__bool__",
}

HEADER = """\
# Generated by scripts/generate_stubs.py -- DO NOT EDIT.
# Regenerate with: make dev-streaming && make stubs
#
# Runtime-introspected stub for the PyO3 `_native` module (ARC-002).
# Parameter names, kinds and defaults come from PyO3 `__text_signature__`;
# value types are `Any` because the native layer does not expose them, and
# constructors are `*args`/`**kwargs` because PyO3 omits `#[new]` signatures.

from types import TracebackType
from typing import Any
"""


def split_top_level(text: str) -> list[str]:
    """Split ``a, b=(1, 2), c`` on commas that are not nested in brackets."""
    parts: list[str] = []
    depth = 0
    current = []
    quote: str | None = None
    for ch in text:
        if quote:
            current.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            current.append(ch)
        elif ch in "([{":
            depth += 1
            current.append(ch)
        elif ch in ")]}":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def sanitize_default(default_text: str) -> str | None:
    """Return the default as a literal, ``...`` for non-literals, or None."""
    try:
        ast.literal_eval(default_text)
    except (ValueError, SyntaxError):
        # Present but not a plain literal (e.g. a rendered expression): stubs
        # spell an unspecified default as `...`.
        return "..."
    return default_text


def render_params(text_sig: str | None, *, implicit_self: bool) -> list[str] | None:
    """Turn a ``__text_signature__`` body into stub parameter strings.

    Returns None when the signature cannot be represented (caller falls back
    to ``*args``/``**kwargs``).
    """
    if not text_sig or not (text_sig.startswith("(") and text_sig.endswith(")")):
        return None
    inner = text_sig[1:-1].strip()
    if not inner:
        return []
    params: list[str] = []
    for raw in split_top_level(inner):
        if raw in (
            "/",
            "*",
            "**",
        ):
            params.append(raw)
            continue
        if "=" in raw:
            name, default = raw.split("=", 1)
            name = name.strip()
            default_text = sanitize_default(default.strip())
        else:
            name = raw.strip()
            default_text = None
        if name.startswith("*"):
            params.append(
                f"{name}: Any"
                if default_text is None
                else f"{name}: Any = {default_text}"
            )
            continue
        if name.startswith("$"):
            # Receiver marker: $self/$cls/$type.
            params.append(name[1:])
            continue
        if keyword.iskeyword(name):
            return None
        rendered = f"{name}: Any"
        if default_text is not None:
            rendered += f" = {default_text}"
        params.append(rendered)
    if implicit_self and params and not params[0].split(":")[0] in ("self", "cls"):
        params.insert(0, "self")
    return params


def render_function(
    name: str,
    text_sig: str | None,
    *,
    is_static: bool = False,
    implicit_self: bool = True,
) -> str:
    params = render_params(text_sig, implicit_self=implicit_self and not is_static)
    if params is None:
        params = ["*args: Any", "**kwargs: Any"]
    indent = "    "
    lines = []
    if is_static:
        lines.append(f"{indent}@staticmethod")
    lines.append(f"{indent}def {name}({', '.join(params)}) -> Any: ...")
    return "\n".join(lines)


def render_class(cls: type) -> list[str]:
    lines = [f"class {cls.__name__}:"]
    emitted_any = False
    for attr_name in sorted(vars(cls)):
        # Keep methods and interesting dunders (__enter__, __exit__, __int__,
        # ...); skip metadata (`__doc__`, `__module__`) and pass-through
        # wrapper descriptors (__repr__/__str__/__hash__ add nothing).
        if attr_name.startswith("__") and attr_name not in DUNDER_METHODS:
            continue
        obj = vars(cls)[attr_name]
        kind = type(obj).__name__
        if kind in (
            "method_descriptor",
            "builtin_function_or_method",
            "wrapper_descriptor",
            "method_wrapper",
        ):
            ts = getattr(obj, "__text_signature__", None)
            if attr_name == "__new__":
                # PyO3 leaves `#[new]` signatures generic; expose the
                # constructor through __init__ instead.
                lines.append(
                    "    def __init__(self, *args: Any, **kwargs: Any) -> None: ..."
                )
                emitted_any = True
                continue
            if attr_name == "__exit__":
                # PYI036: the context-manager protocol has fixed parameter
                # types; the native signature only carries the names.
                lines.append(
                    "    def __exit__(self, exc_type: type[BaseException] | None,"
                    " exc_value: BaseException | None, traceback: TracebackType | None)"
                    " -> Any: ..."
                )
                emitted_any = True
                continue
            lines.append(render_function(attr_name, ts))
            emitted_any = True
        elif kind == "staticmethod":
            ts = getattr(obj.__func__, "__text_signature__", None)
            lines.append(render_function(attr_name, ts, is_static=True))
            emitted_any = True
        elif kind == "classmethod":
            ts = getattr(obj.__func__, "__text_signature__", None)
            lines.append("    @classmethod")
            params = render_params(ts, implicit_self=False)
            if params is None or not params or params[0].split(":")[0] != "cls":
                params = (["cls"] + params) if params else ["cls"]
            lines.append(f"    def {attr_name}({', '.join(params)}) -> Any: ...")
            emitted_any = True
        elif kind == "getset_descriptor":
            lines.append("    @property")
            lines.append(f"    def {attr_name}(self) -> Any: ...")
            lines.append(f"    @{attr_name}.setter")
            lines.append(f"    def {attr_name}(self, value: Any) -> None: ...")
            emitted_any = True
        elif kind == "str":
            continue
        else:
            # Enum-style members (values of the class's own type) and any
            # other class-level constants.
            if type(obj) is cls:
                if keyword.iskeyword(attr_name):
                    # E.g. UnderlineStyle.None -- not representable in Python
                    # syntax; tracked in SKIPPED_MEMBERS for the report.
                    SKIPPED_MEMBERS.append(f"{cls.__name__}.{attr_name}")
                    continue
                lines.append(f"    {attr_name}: {cls.__name__}")
                emitted_any = True
            # Anything else (uncommon) is intentionally skipped.
    if not emitted_any:
        lines.append("    pass")
    return lines


def main() -> None:
    classes: dict[str, type] = {}
    functions: dict[str, object] = {}
    constants: dict[str, object] = {}
    for name in dir(native):
        if name.startswith("_"):
            continue
        obj = getattr(native, name)
        kind = type(obj).__name__
        if kind == "type":
            classes[name] = obj
        elif kind == "builtin_function_or_method":
            functions[name] = obj
        elif isinstance(obj, str):
            constants[name] = obj
        # Anything else unexpected: fail loudly rather than silently drop.
        else:
            msg = f"Unhandled module member kind for {name!r}: {kind}"
            raise SystemExit(msg)

    out: list[str] = [HEADER]

    for name in sorted(constants):
        value = constants[name]
        out.append(f"\n{name}: str = {value!r}")

    for cname in sorted(classes):
        out.append("")
        out.extend(render_class(classes[cname]))

    for fname in sorted(functions):
        ts = getattr(functions[fname], "__text_signature__", None)
        out.append("")
        out.append(render_function(fname, ts, implicit_self=False).strip())

    text = "\n".join(out).rstrip() + "\n"
    ast.parse(text, filename=str(OUT_PATH))

    # Coverage self-check: every public module member must appear.
    stub_names = set(constants) | set(classes) | set(functions)
    module_names = {n for n in dir(native) if not n.startswith("_")}
    missing = module_names - stub_names
    if missing:
        msg = f"Stub is missing module members: {sorted(missing)}"
        raise SystemExit(msg)

    OUT_PATH.write_text(text, encoding="utf-8")
    n_methods = text.count("    def ")
    n_props = text.count("    @property")
    print(f"Wrote {OUT_PATH}")
    print(
        f"  {len(classes)} classes, {n_methods} methods/constructors, "
        f"{n_props} properties, {len(functions)} functions, {len(constants)} constants"
    )
    if SKIPPED_MEMBERS:
        print(f"  skipped (unrepresentable names): {', '.join(SKIPPED_MEMBERS)}")


if __name__ == "__main__":
    main()
