#!/usr/bin/env python3
"""Generate ``python/par_term_emu_core_rust/_native.pyi`` from the built native module.

ARC-002: runtime-introspection stub generation. The PyO3 ``_native`` module is
introspected at runtime (classes, methods, properties, module functions and
constants) and emitted as a parseable ``.pyi`` stub so the
``Typing :: Typed`` classifier is honest.

Usage (requires a built module; ``make dev-streaming`` captures the widest
method surface, ``make dev`` covers the same class/function names):

    uv run python scripts/generate_stubs.py

Known limitations (deliberate, see AUDIT.md ARC-002 and DOC-116):
- Docstrings are copied from ``__doc__``. Return types come from a
  Google-style ``Returns:`` line whose first token is a type over builtins
  and native classes, and parameter types from ``name (TYPE):`` Args
  entries. Everything else, including every property, is ``Any``.
- Properties are emitted with both a getter and a setter; read-only
  properties are over-promised in the stub (harmless for type checking).
- Constructors fall back to ``*args``/``**kwargs`` only for classes whose
  ``#[new]`` exposes no ``__text_signature__`` (ENH-030; PyO3 0.29 sets the
  class-level signature from ``#[new]``/``#[pyo3(signature=…)]``).

The script self-checks its output with :mod:`ast` and verifies that every
public ``dir()`` member of the module appears in the stub.
"""

from __future__ import annotations

import ast
import inspect
import keyword
import re
from pathlib import Path

import par_term_emu_core_rust._native as native

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "python" / "par_term_emu_core_rust" / "_native.pyi"

# Members that exist at runtime but cannot be spelled in a stub (Python
# keywords used as attribute names, e.g. UnderlineStyle.None).
SKIPPED_MEMBERS: list[str] = []

# Dunders worth emitting when the class defines them (protocol methods pyright
# checks, e.g. context-manager and conversion protocols).
DUNDER_METHODS = {
    "__init__",
    "__new__",
    "__enter__",
    "__exit__",
    "__aenter__",
    "__aexit__",
    "__iter__",
    "__next__",
    "__len__",
    "__getitem__",
    "__setitem__",
    "__contains__",
    "__call__",
    "__int__",
    "__float__",
    "__str__",
    "__index__",
    "__copy__",
    "__deepcopy__",
    "__bool__",
}

HEADER = """\
# Generated by scripts/generate_stubs.py -- DO NOT EDIT.
# Regenerate with: make dev-streaming && make stubs
#
# Runtime-introspected stub for the PyO3 `_native` module (ARC-002).
# Parameter names, kinds and defaults come from PyO3 `__text_signature__`
# (methods, and constructors via the class-level signature — ENH-030).
# Docstrings are copied from `__doc__` (DOC-116). Return types come from a
# Google-style `Returns:` line whose first token is a type over builtins and
# native classes, and parameter types from `name (TYPE):` Args entries.
# Everything else, including every property, is `Any`.

from types import TracebackType
from typing import Any
"""

BUILTIN_TYPE_NAMES = {
    "int",
    "float",
    "str",
    "bytes",
    "bool",
    "list",
    "dict",
    "tuple",
    "set",
    "object",
    "None",
}
# AST nodes a docstring type expression may contain: names, `None`,
# subscripts (`list[int]`), tuples inside subscripts and `X | Y` unions.
# Anything else (attributes like `asyncio.Queue`, `int or None`, calls) is
# prose, not a type.
ALLOWED_TYPE_NODES = (
    ast.Expression,
    ast.Name,
    ast.Load,
    ast.Constant,
    ast.Subscript,
    ast.Tuple,
    ast.BinOp,
    ast.BitOr,
)
RETURNS_RE = re.compile(r"^Returns:[ \t]*\n[ \t]+([^\n:]+?):", re.MULTILINE)
ARGS_BLOCK_RE = re.compile(r"^Args:[ \t]*\n((?:[ \t]+.*\n?)+)", re.MULTILINE)
TYPED_ARG_RE = re.compile(r"^[ \t]+([A-Za-z_]\w*) \(([^)]+)\):", re.MULTILINE)


def split_top_level(text: str) -> list[str]:
    """Split ``a, b=(1, 2), c`` on commas that are not nested in brackets."""
    parts: list[str] = []
    depth = 0
    current = []
    quote: str | None = None
    for ch in text:
        if quote:
            current.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "\"'":
            quote = ch
            current.append(ch)
        elif ch in "([{":
            depth += 1
            current.append(ch)
        elif ch in ")]}":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    tail = "".join(current).strip()
    if tail:
        parts.append(tail)
    return parts


def sanitize_default(default_text: str) -> str | None:
    """Return the default as a literal, ``...`` for non-literals, or None."""
    try:
        ast.literal_eval(default_text)
    except (ValueError, SyntaxError):
        # Present but not a plain literal (e.g. a rendered expression): stubs
        # spell an unspecified default as `...`.
        return "..."
    return default_text


def doc_type(expr: str, known: set[str]) -> str | None:
    """Return ``expr`` when it is a type expression over builtins and native classes, else None."""
    try:
        tree = ast.parse(expr.strip(), mode="eval")
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if not isinstance(node, ALLOWED_TYPE_NODES):
            return None
        if isinstance(node, ast.BinOp) and not isinstance(node.op, ast.BitOr):
            return None
        if isinstance(node, ast.Name) and node.id not in BUILTIN_TYPE_NAMES | known:
            return None
        if isinstance(node, ast.Constant) and node.value is not None:
            return None
    return expr.strip()


def returns_type(doc: str | None, known: set[str]) -> str:
    """Return type named by the docstring's ``Returns:`` section, or ``Any``."""
    m = RETURNS_RE.search(inspect.cleandoc(doc)) if doc else None
    return (doc_type(m.group(1), known) if m else None) or "Any"


def arg_types(doc: str | None, known: set[str]) -> dict[str, str]:
    """Map parameter names to types from ``name (TYPE):`` Args entries."""
    if not doc:
        return {}
    block = ARGS_BLOCK_RE.search(inspect.cleandoc(doc))
    if not block:
        return {}
    out: dict[str, str] = {}
    for name, expr in TYPED_ARG_RE.findall(block.group(1)):
        typed = doc_type(expr, known)
        if typed:
            out[name] = typed
    return out


def render_docstring(doc: str | None, indent: str) -> list[str]:
    """Render ``doc`` as stub docstring lines at ``indent`` (empty when absent)."""
    if not doc or not doc.strip():
        return []
    text = inspect.cleandoc(doc).replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    lines = text.splitlines()
    if len(lines) == 1:
        line = lines[0]
        if line.endswith('"'):
            # `"""say "hi""""` does not parse; escape the final quote.
            line = line[:-1] + '\\"'
        return [f'{indent}"""{line}"""']
    return [
        f'{indent}"""{lines[0]}',
        *[f"{indent}{line}" if line else "" for line in lines[1:]],
        f'{indent}"""',
    ]


def render_params(
    text_sig: str | None,
    *,
    implicit_self: bool,
    types: dict[str, str] | None = None,
) -> list[str] | None:
    """Turn a ``__text_signature__`` body into stub parameter strings.

    ``types`` maps parameter names to annotations (from the docstring);
    unlisted parameters are ``Any``. Returns None when the signature cannot be
    represented (caller falls back to ``*args``/``**kwargs``).
    """
    if not text_sig or not (text_sig.startswith("(") and text_sig.endswith(")")):
        return None
    inner = text_sig[1:-1].strip()
    if not inner:
        return []
    params: list[str] = []
    for raw in split_top_level(inner):
        if raw in (
            "/",
            "*",
            "**",
        ):
            params.append(raw)
            continue
        if "=" in raw:
            name, default = raw.split("=", 1)
            name = name.strip()
            default_text = sanitize_default(default.strip())
        else:
            name = raw.strip()
            default_text = None
        if name.startswith("*"):
            params.append(
                f"{name}: Any"
                if default_text is None
                else f"{name}: Any = {default_text}"
            )
            continue
        if name.startswith("$"):
            # Receiver marker: $self/$cls/$type.
            params.append(name[1:])
            continue
        if keyword.iskeyword(name):
            return None
        annotation = (types or {}).get(name, "Any")
        if default_text == "None" and annotation != "Any" and "None" not in annotation:
            # Docs name the value type; a `None` default makes it optional.
            annotation = f"{annotation} | None"
        rendered = f"{name}: {annotation}"
        if default_text is not None:
            rendered += f" = {default_text}"
        params.append(rendered)
    if implicit_self and params and not params[0].split(":")[0] in ("self", "cls"):
        params.insert(0, "self")
    return params


def render_function(
    name: str,
    text_sig: str | None,
    *,
    is_static: bool = False,
    implicit_self: bool = True,
    doc: str | None = None,
    known: set[str] | frozenset[str] = frozenset(),
    indent: str = "    ",
) -> str:
    ret = returns_type(doc, set(known))
    types = arg_types(doc, set(known))
    params = render_params(
        text_sig, implicit_self=implicit_self and not is_static, types=types
    )
    if params is None:
        params = ["*args: Any", "**kwargs: Any"]
    lines = []
    if is_static:
        lines.append(f"{indent}@staticmethod")
    docstring = render_docstring(doc, indent + "    ")
    if docstring:
        lines.append(f"{indent}def {name}({', '.join(params)}) -> {ret}:")
        lines.extend(docstring)
    else:
        lines.append(f"{indent}def {name}({', '.join(params)}) -> {ret}: ...")
    return "\n".join(lines)


def render_class(cls: type, known: set[str]) -> list[str]:
    lines = [f"class {cls.__name__}:"]
    class_doc = render_docstring(cls.__doc__, "    ")
    lines.extend(class_doc)
    emitted_any = bool(class_doc)
    for attr_name in sorted(vars(cls)):
        # Keep methods and interesting dunders (__enter__, __exit__, __int__,
        # ...); skip metadata (`__doc__`, `__module__`) and pass-through
        # wrapper descriptors (__repr__/__str__/__hash__ add nothing).
        if attr_name.startswith("__") and attr_name not in DUNDER_METHODS:
            continue
        obj = vars(cls)[attr_name]
        kind = type(obj).__name__
        if kind in (
            "method_descriptor",
            "builtin_function_or_method",
            "wrapper_descriptor",
            "method_wrapper",
        ):
            ts = getattr(obj, "__text_signature__", None)
            if attr_name == "__new__":
                # ENH-030: PyO3 0.29 sets the CLASS-level
                # `__text_signature__` from `#[new]`/`#[pyo3(signature=…)]`
                # (e.g. Terminal's '(cols, rows, scrollback=10000)'), while
                # `__new__`'s own descriptor stays generic. Render __init__
                # from the class signature; `*args`/`**kwargs` only when the
                # class exposes none.
                cls_ts = getattr(cls, "__text_signature__", None)
                params = render_params(cls_ts, implicit_self=True)
                if params is None:
                    params = ["*args: Any", "**kwargs: Any"]
                lines.append(f"    def __init__({', '.join(params)}) -> None: ...")
                emitted_any = True
                continue
            if attr_name == "__exit__":
                # PYI036: the context-manager protocol has fixed parameter
                # types; the native signature only carries the names.
                lines.append(
                    "    def __exit__(self, exc_type: type[BaseException] | None,"
                    " exc_value: BaseException | None, traceback: TracebackType | None)"
                    " -> Any: ..."
                )
                emitted_any = True
                continue
            lines.append(render_function(attr_name, ts, doc=obj.__doc__, known=known))
            emitted_any = True
        elif kind == "staticmethod":
            ts = getattr(obj.__func__, "__text_signature__", None)
            lines.append(
                render_function(
                    attr_name,
                    ts,
                    is_static=True,
                    doc=obj.__func__.__doc__,
                    known=known,
                )
            )
            emitted_any = True
        elif kind == "classmethod":
            ts = getattr(obj.__func__, "__text_signature__", None)
            doc = obj.__func__.__doc__
            lines.append("    @classmethod")
            params = render_params(ts, implicit_self=False, types=arg_types(doc, known))
            if params is None or not params or params[0].split(":")[0] != "cls":
                params = (["cls"] + params) if params else ["cls"]
            signature = f"    def {attr_name}({', '.join(params)}) -> {returns_type(doc, known)}:"
            docstring = render_docstring(doc, "        ")
            if docstring:
                lines.append(signature)
                lines.extend(docstring)
            else:
                lines.append(f"{signature} ...")
            emitted_any = True
        elif kind == "getset_descriptor":
            lines.append("    @property")
            prop_doc = render_docstring(obj.__doc__, "        ")
            if prop_doc:
                lines.append(f"    def {attr_name}(self) -> Any:")
                lines.extend(prop_doc)
            else:
                lines.append(f"    def {attr_name}(self) -> Any: ...")
            lines.append(f"    @{attr_name}.setter")
            lines.append(f"    def {attr_name}(self, value: Any) -> None: ...")
            emitted_any = True
        elif kind == "str":
            continue
        else:
            # Enum-style members (values of the class's own type) and any
            # other class-level constants.
            if type(obj) is cls:
                if keyword.iskeyword(attr_name):
                    # E.g. UnderlineStyle.None -- not representable in Python
                    # syntax; tracked in SKIPPED_MEMBERS for the report.
                    SKIPPED_MEMBERS.append(f"{cls.__name__}.{attr_name}")
                    continue
                lines.append(f"    {attr_name}: {cls.__name__}")
                emitted_any = True
            # Anything else (uncommon) is intentionally skipped.
    if not emitted_any:
        lines.append("    pass")
    return lines


def main() -> None:
    classes: dict[str, type] = {}
    functions: dict[str, object] = {}
    constants: dict[str, object] = {}
    for name in dir(native):
        if name.startswith("_"):
            continue
        obj = getattr(native, name)
        kind = type(obj).__name__
        if kind == "type":
            classes[name] = obj
        elif kind == "builtin_function_or_method":
            functions[name] = obj
        elif isinstance(obj, (str, bool)):
            constants[name] = obj
        # Anything else unexpected: fail loudly rather than silently drop.
        else:
            msg = f"Unhandled module member kind for {name!r}: {kind}"
            raise SystemExit(msg)

    out: list[str] = [HEADER]

    # The non-streaming build ships a placeholder StreamingConfig whose
    # constructor is '()' — a stub generated from it would silently lie
    # about the real surface (project memory: stub-regen-needs-dev-streaming).
    if getattr(native.StreamingConfig, "__text_signature__", None) in (None, "()"):
        msg = (
            "StreamingConfig has no real constructor signature — the module "
            "was built without the streaming feature. Run "
            "`make dev-streaming` before `make stubs`."
        )
        raise SystemExit(msg)

    for name in sorted(constants):
        value = constants[name]
        out.append(f"\n{name}: {type(value).__name__} = {value!r}")

    known = set(classes)
    for cname in sorted(classes):
        out.append("")
        out.extend(render_class(classes[cname], known))

    for fname in sorted(functions):
        func = functions[fname]
        ts = getattr(func, "__text_signature__", None)
        out.append("")
        out.append(
            render_function(
                fname,
                ts,
                implicit_self=False,
                doc=getattr(func, "__doc__", None),
                known=known,
                indent="",
            )
        )

    text = "\n".join(out).rstrip() + "\n"
    ast.parse(text, filename=str(OUT_PATH))
    # Pre-format, every `def` is one line, so the return annotation is on it.
    typed_returns = len(
        re.findall(r"^\s*def .*\) -> (?!Any:|None:)", text, re.MULTILINE)
    )

    # Coverage self-check: every public module member must appear.
    stub_names = set(constants) | set(classes) | set(functions)
    module_names = {n for n in dir(native) if not n.startswith("_")}
    missing = module_names - stub_names
    if missing:
        msg = f"Stub is missing module members: {sorted(missing)}"
        raise SystemExit(msg)

    OUT_PATH.write_text(text, encoding="utf-8")
    n_methods = text.count("    def ")
    n_props = text.count("    @property")
    print(f"Wrote {OUT_PATH}")
    print(
        f"  {len(classes)} classes, {n_methods} methods/constructors, "
        f"{n_props} properties, {len(functions)} functions, {len(constants)} constants"
    )
    print(f"  typed returns: {typed_returns}")
    if SKIPPED_MEMBERS:
        print(f"  skipped (unrepresentable names): {', '.join(SKIPPED_MEMBERS)}")


if __name__ == "__main__":
    main()
