/*
 * terminal_core.h — C API for embedding the par-term emulator core.
 *
 * GENERATED by cbindgen from src/ffi.rs (ENH-027); do not edit — regenerate
 * with `make ffi-header`. The TERM_* constants and _Static_assert layout
 * pins live in terminal_core_layout.h, included at the end of this file.
 *
 * Ownership contract:
 * - terminal_get_state returns a heap-allocated SharedState owned by the
 *   caller; release it with terminal_free_state. Its `title`, `cwd`, and
 *   `cells` pointers are valid only until that call.
 * - The vtable (including its user_data) must stay valid for the lifetime
 *   of the observer registration.
 *
 * Cross-cutting contract notes (DOC-071):
 * - Reads target the ACTIVE grid: while the alternate screen is active,
 *   terminal_scrollback_count returns 0 — the alternate screen has no
 *   scrollback.
 * - Handles are single-threaded: no concurrent calls on one Terminal.
 * - No entry point catches a panic. A panic inside any call aborts the
 *   host process (Rust 1.81+ abort-on-FFI-unwind semantics, ARC-087).
 * - Allocation failure aborts the process; this surface has no error
 *   channel, so out-of-memory is fatal by design.
 *
 * ABI version (ARC-063): TERM_CORE_ABI_VERSION (terminal_core_layout.h) is
 * the contract version of this header. A binary compares it against
 * terminal_abi_version() at runtime to detect a layout mismatch; bump the
 * macro and the Rust constant together on any layout or contract change.
 */


#ifndef PAR_TERM_EMU_CORE_TERMINAL_CORE_H
#define PAR_TERM_EMU_CORE_TERMINAL_CORE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * A terminal emulator covering VT100/VT220/VT320/VT420/VT520 sequences with
 * iTerm2 feature parity: scrollback, true color, Sixel/iTerm2/Kitty graphics,
 * mouse reporting, and shell integration.
 *
 * State is grouped into `pub(crate)` sub-structs by feature area (ARC-001).
 * Feed input bytes through [`Terminal::process`] and query grid/cursor state
 * through the accessor methods.
 */
typedef struct Terminal Terminal;

/**
 * An inclusive [start, end] range of dirty screen rows, in coalesced form.
 */
typedef struct {
  /**
   * First dirty row (0-indexed, inclusive)
   */
  uint32_t start;
  /**
   * Last dirty row (0-indexed, inclusive)
   */
  uint32_t end;
} TermRowRange;

/**
 * A single terminal cell in a C-compatible layout.
 *
 * The `text` field holds the UTF-8 bytes of the base character (up to 4 bytes
 * for any Unicode scalar value). `text_len` indicates how many bytes are valid.
 */
typedef struct {
  /**
   * UTF-8 encoded character bytes (up to 4 bytes for any Unicode scalar)
   */
  uint8_t text[4];
  /**
   * Number of valid bytes in `text`
   */
  uint8_t text_len;
  /**
   * Foreground color — red component
   */
  uint8_t fg_r;
  /**
   * Foreground color — green component
   */
  uint8_t fg_g;
  /**
   * Foreground color — blue component
   */
  uint8_t fg_b;
  /**
   * Background color — red component
   */
  uint8_t bg_r;
  /**
   * Background color — green component
   */
  uint8_t bg_g;
  /**
   * Background color — blue component
   */
  uint8_t bg_b;
  /**
   * Bitfield of cell attributes (bold, italic, etc.) — see `CellBitflags`
   */
  uint16_t attrs;
  /**
   * Display width of the character (typically 1 or 2)
   */
  uint8_t width;
} SharedCell;

/**
 * Cursor position and style, C-compatible.
 */
typedef struct {
  uint32_t col;
  uint32_t row;
  /**
   * Whether the cursor is visible (DECTCEM)
   */
  bool visible;
  /**
   * Cursor style code: 0 blinking block, 1 steady block, 2 blinking
   * underline, 3 steady underline, 4 blinking bar, 5 steady bar
   */
  uint8_t style;
} TermCursorState;

/**
 * Terminal mode state a renderer needs per frame, C-compatible.
 */
typedef struct {
  /**
   * Alternate screen buffer active
   */
  bool alt_screen;
  /**
   * Bracketed paste mode (paste input should be wrapped in ESC[200~…201~)
   */
  bool bracketed_paste;
  /**
   * Application cursor keys (arrows encode as SS3, not CSI)
   */
  bool application_cursor;
  /**
   * Origin mode (DECOM) — cursor addresses are scroll-region-relative
   */
  bool origin_mode;
  /**
   * Insert mode (IRM) — typed characters shift the row right
   */
  bool insert_mode;
  /**
   * Autowrap (DECAWM)
   */
  bool auto_wrap;
  /**
   * Mouse tracking mode (0=Off, 1=X10, 2=Normal, 3=ButtonEvent, 4=AnyEvent)
   */
  uint8_t mouse_mode;
  /**
   * Kitty keyboard protocol progressive-enhancement flags
   */
  uint16_t kitty_flags;
  uint32_t cols;
  uint32_t rows;
} TermModeState;

/**
 * A key event in a C-compatible layout.
 *
 * For `TermKey::Char`, `codepoint` is the character as it should be typed:
 * the shifted glyph for plain typing (`'A'` for Shift+A, `'ä'` for ä), or
 * the base form (`'a'`) when Ctrl/Alt modifiers drive the encoding.
 */
typedef struct {
  /**
   * The key as a raw `TERM_KEY_*` value: C and Swift fill this struct
   * with a bare `uint16_t`, and a Rust enum reference is only sound for
   * a valid discriminant (QA-151) — every read goes through
   * [`TermKeyEvent::key`], which maps unknown values to `Unknown`.
   */
  uint16_t key;
  /**
   * Bitfield of [`modifiers`] constants.
   */
  uint8_t modifiers;
  /**
   * Reserved; must be zero.
   */
  uint8_t _pad;
  /**
   * Unicode scalar for `TermKey::Char`, 0 otherwise.
   */
  uint32_t codepoint;
} TermKeyEvent;

/**
 * A complete, C-compatible snapshot of the terminal state.
 *
 * All heap-allocated fields (`title`, `cwd`, `cells`) are owned by this struct
 * and freed on `Drop`.
 */
typedef struct {
  /**
   * Number of columns in the terminal grid
   */
  uint32_t cols;
  /**
   * Number of rows in the terminal grid
   */
  uint32_t rows;
  /**
   * Current cursor column (0-indexed)
   */
  uint32_t cursor_col;
  /**
   * Current cursor row (0-indexed)
   */
  uint32_t cursor_row;
  /**
   * Whether the cursor is visible
   */
  bool cursor_visible;
  /**
   * Whether the alternate screen buffer is active
   */
  bool alt_screen_active;
  /**
   * Mouse tracking mode (0=Off, 1=X10, 2=Normal, 3=ButtonEvent, 4=AnyEvent)
   */
  uint8_t mouse_mode;
  /**
   * Terminal title as a NUL-terminated C string (owned)
   */
  char *title;
  /**
   * Length of the title string in bytes (not counting NUL)
   */
  uint32_t title_len;
  /**
   * Current working directory as a NUL-terminated C string (owned), or null
   */
  char *cwd;
  /**
   * Length of the cwd string in bytes (not counting NUL), 0 if cwd is null
   */
  uint32_t cwd_len;
  /**
   * Pointer to an array of `cell_count` SharedCell values (owned)
   */
  SharedCell *cells;
  /**
   * Total number of cells (cols * rows)
   */
  uint32_t cell_count;
  /**
   * Number of lines currently in the scrollback buffer
   */
  uint32_t scrollback_lines;
  /**
   * Total lines (visible + scrollback)
   */
  uint32_t total_lines;
} SharedState;

/**
 * The callback shape shared by every [`TerminalObserverVtable`] slot:
 * receives the vtable's `user_data` and a NUL-terminated, Debug-formatted
 * event description valid only for the duration of the call. A named alias
 * (not an inline type) so cbindgen emits the `term_event_cb` typedef the
 * C header promises (ENH-027).
 */
typedef void (*term_event_cb)(void *user_data, const char *event_text);

/**
 * A C-compatible vtable for terminal event observation.
 *
 * Each function pointer receives the `user_data` pointer and a
 * Debug-formatted (`{:?}`) event description as a NUL-terminated C string.
 * The payload is DIAGNOSTIC TEXT, not a stable format: it changes whenever
 * the Rust event enum changes — parse it only for logging. The callee must
 * NOT free the event string — it is owned by the caller and valid only for
 * the duration of the callback.
 *
 * Callbacks fire inline while the terminal is processing input. A callback
 * must NOT re-enter the FFI on the same `Terminal` handle (any
 * `terminal_*` function): the terminal is mutably borrowed for the
 * duration of the dispatch, so re-entry aliases `&`/`&mut` — undefined
 * behavior. Queue what you need and call back after `terminal_feed`
 * returns.
 */
typedef struct {
  /**
   * Called for zone lifecycle events
   */
  term_event_cb on_zone_event;
  /**
   * Called for command/shell integration events
   */
  term_event_cb on_command_event;
  /**
   * Called for environment change events
   */
  term_event_cb on_environment_event;
  /**
   * Called for screen content events
   */
  term_event_cb on_screen_event;
  /**
   * Called for ALL events (catch-all)
   */
  term_event_cb on_event;
  /**
   * Opaque pointer passed to every callback
   */
  void *user_data;
} TerminalObserverVtable;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * The ABI version this library implements. A binary detects a mismatch
 * by comparing this call's return against its compiled-in header macro.
 * Safe to call at any time — it touches no terminal state.
 */
uint32_t terminal_abi_version(void);

/**
 * Create a terminal for C embedding.
 *
 * Returns NULL when `cols` or `rows` is 0. Allocation failure aborts the
 * process — this surface has no error channel, so OOM is fatal by design.
 *
 * # Safety
 * Caller owns the returned `Terminal` and must release it with
 * `terminal_free`.
 */
Terminal *terminal_create(uint32_t cols, uint32_t rows, uint32_t scrollback);

/**
 * Free a `Terminal` created by `terminal_create`.
 *
 * # Safety
 * `term` must have been returned by `terminal_create` and must not be
 * used after this call.
 */
void terminal_free(Terminal *term);

/**
 * Feed raw PTY/application output bytes into the terminal (VT parsing).
 *
 * # Safety
 * `bytes` must be valid for reads of `len` bytes. `term` must be a valid
 * pointer to a `Terminal`.
 */
void terminal_feed(Terminal *term, const uint8_t *bytes, uint32_t len);

/**
 * Resize the terminal grid. A zero `cols` or `rows` is a no-op.
 *
 * # Safety
 * `term` must be a valid pointer to a `Terminal`.
 */
void terminal_resize(Terminal *term, uint32_t cols, uint32_t rows);

/**
 * Coalesce the dirty-row generations into inclusive row ranges.
 *
 * Writes up to `cap` ranges into `out` (caller-owned) and returns the
 * total range count — if the return exceeds `cap`, call again with a
 * larger buffer. A renderer redraws only rows inside the returned ranges.
 * Serves the built-in default consumer; `terminal_mark_clean` advances it.
 *
 * # Safety
 * `out` must be valid for writes of `cap` `TermRowRange` values. It may
 * be NULL only as a sizing call, with `cap` 0 — the call then just
 * returns the total range count.
 */
uint32_t terminal_dirty_ranges(const Terminal *term, TermRowRange *out, uint32_t cap);

/**
 * Current damage generation. A renderer remembers this value between
 * frames and passes it to `terminal_dirty_ranges_since` to observe only
 * what changed since — independent of `terminal_mark_clean`, which
 * advances the default consumer's generation and cannot hide damage from
 * generation consumers (ENH-025).
 *
 * # Safety
 * `term` must be a valid pointer to a `Terminal`.
 */
uint64_t terminal_damage_generation(const Terminal *term);

/**
 * Coalesced dirty-row ranges since generation `gen`, from an earlier
 * `terminal_damage_generation` call. Same buffer contract as
 * `terminal_dirty_ranges`: fills up to `cap` ranges into `out` and
 * returns the total count; `out` may be NULL with `cap` 0 as a sizing
 * call. A screen switch dirties every row of the newly visible grid.
 *
 * # Safety
 * `out` must be valid for writes of `cap` `TermRowRange` values, or NULL
 * with `cap` 0 for a sizing call. `term` must be a valid pointer to a
 * `Terminal`.
 */
uint32_t terminal_dirty_ranges_since(const Terminal *term,
                                     uint64_t gen,
                                     TermRowRange *out,
                                     uint32_t cap);

/**
 * Mark the screen clean (all damage consumed).
 *
 * # Safety
 * `term` must be a valid pointer to a `Terminal`.
 */
void terminal_mark_clean(Terminal *term);

/**
 * Copy a run of grid cells into a caller-owned buffer (pinned readback —
 * no allocation, no full-grid copy). Returns the number of cells written;
 * with `out` NULL it returns the number of cells available from
 * `col_start` (the sizing answer) instead. Reads target the active grid,
 * so while the alternate screen is active there is no scrollback.
 *
 * # Safety
 * `out` must be valid for writes of `cap` `SharedCell` values, or NULL
 * with `cap` 0 for a sizing call.
 */
uint32_t terminal_read_row(const Terminal *term,
                           uint32_t row,
                           uint32_t col_start,
                           SharedCell *out,
                           uint32_t cap);

/**
 * Copy a run of scrollback cells into a caller-owned buffer.
 * `line` indexes scrollback from the oldest (0) to the newest
 * (`scrollback_count - 1`). Returns the number of cells written; with
 * `out` NULL it returns the number of cells available from `col_start`
 * (the sizing answer) instead.
 *
 * # Safety
 * `out` must be valid for writes of `cap` `SharedCell` values, or NULL
 * with `cap` 0 for a sizing call.
 */
uint32_t terminal_read_scrollback_row(const Terminal *term,
                                      uint32_t line,
                                      uint32_t col_start,
                                      SharedCell *out,
                                      uint32_t cap);

/**
 * Number of lines currently held in scrollback.
 *
 * # Safety
 * `term` must be a valid pointer to a `Terminal`.
 */
uint32_t terminal_scrollback_count(const Terminal *term);

/**
 * Read cursor position/style.
 *
 * # Safety
 * `out` must be valid for writes of one `TermCursorState`.
 */
void terminal_get_cursor(const Terminal *term, TermCursorState *out);

/**
 * Read per-frame mode state.
 *
 * # Safety
 * `out` must be valid for writes of one `TermModeState`.
 */
void terminal_get_modes(const Terminal *term, TermModeState *out);

/**
 * Encode a key event against the terminal's negotiated input state
 * (application cursor keys, kitty keyboard flags). Writes up to `cap`
 * bytes into `out` (caller-owned) and returns the total encoded length —
 * if the return exceeds `cap`, call again with a larger buffer. The
 * returned bytes are what a frontend would write to the PTY.
 *
 * # Safety
 * `ev` must be valid for reads of one `TermKeyEvent`; `out` must be valid
 * for writes of `cap` bytes, or NULL with `cap` 0 to fetch the total
 * encoded length.
 */
uint32_t terminal_encode_key(const Terminal *term,
                             const TermKeyEvent *ev,
                             uint8_t *out,
                             uint32_t cap);

/**
 * Create a snapshot of the terminal's current state.
 *
 * The caller owns the returned `SharedState` and must free it by calling
 * `terminal_free_state`.
 *
 * # Safety
 * `term` must be a valid pointer to a `Terminal`.
 */
SharedState *terminal_get_state(const Terminal *term);

/**
 * Free a `SharedState` previously returned by `terminal_get_state`.
 *
 * # Safety
 * `state` must be a pointer previously returned by `terminal_get_state`,
 * and must not be used after this call.
 */
void terminal_free_state(SharedState *state);

/**
 * Register an FFI observer on the terminal.
 *
 * Returns an observer ID that can be passed to `terminal_remove_observer`.
 *
 * # Safety
 * `term` must be a valid, mutable pointer to a `Terminal`.
 * The `vtable` must remain valid (including its `user_data`) for as long as
 * the observer is registered.
 */
uint64_t terminal_add_observer(Terminal *term, TerminalObserverVtable vtable);

/**
 * Remove a previously registered observer.
 *
 * Returns `true` if the observer was found and removed.
 *
 * # Safety
 * `term` must be a valid, mutable pointer to a `Terminal`.
 */
bool terminal_remove_observer(Terminal *term, uint64_t id);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PAR_TERM_EMU_CORE_TERMINAL_CORE_H */

#include "terminal_core_layout.h"
